# Generated by Django 4.1 on 2023-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_auto_20230530_0248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
