# Generated by Django 3.0.3 on 2023-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230530_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='photos/product/')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
