# Generated by Django 3.0.3 on 2023-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
