# Generated by Django 4.1 on 2023-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_review_hospital_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
