# Generated by Django 3.2.6 on 2021-08-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
